name: linting
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: 17.9.1

        steps:
            - uses: actions/checkout@v2
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Clear npm cache
              run: npm cache clean --force
            - name: install modules
              run: npm install
            - name: build production project
              run: npm run build:prod
            - name: linting typescript
              run: npm run lint:ts
            - name: linting css
              run: npm run lint:scss
            - name: unit testing
              run: npm run test:unit
